package edu.berkeley.forum.dicts

import scala.collection.mutable.HashMap
import edu.berkeley.nlp.futile.fig.basic.IOUtils
import edu.berkeley.nlp.futile.util.Logger

object ProductToClusterMap {

  
  
//- bulk accounts for online service X
//- malware installs
//- Web traffic
//- crypter software/service
//- email lists (for spamming)
//- virtual hosting
//- hacked web services (e.g. cpanels)
//- credit card dumps
  
  val a = "account"
  val ba = "bulk account"
  val ha = "hacked account"
  val c = "crypter"
  val pr = "proxy"
  val st = "DDoS service"
  val h = "hacking service"
  val m = "malware"
  val mi= "malware installs"
  val cs = "crypting service"
  val ho = "hosting"
  val hs = "hacked server"
  val t = "traffic"
  val ss = "spamming service"
  val sp = "spam tool"
  val d = "development"
  val b = "benigns"
  val vgs = "video game service"
  val vg = "video"
  val u = "unknown"
  
  val s = "service"
  val p = "product"
  
  val other = "other"
  
  // Old labels
//  val mi = "malware installs"
//  val wt = "web traffic"
//  val c = "crypter"
//  val el = "email lists"
//  val vh = "virtual hosting"
//  val hws = "hacked web services"
//  val cc = "cc dumps"
//  val exploits = "exploits"
//  val other = "other"
  
  // Main ones I'm unsure about:
  // root
  // rdps
  // mail: sometimes people wants mails+pws
  // (server, access, site, hack) is all a cluster about compromising things
  // dbs: various kinds of dbs
  // proxi
  // pack: lots of exploit packs, but maybe others?
  // VPS
  
//  val gregProductTypeMapping = new HashMap[String,String]() ++
//    Seq("traffic" -> wt,
//        "root" -> hws,
//        "exploits" -> exploits,
//        "coder" -> other,
//        "list" -> el,
//        "server" -> hws,
//        "access" -> hws,
//        "mail" -> el,
//        "crypter" -> c,
//        "hack" -> hws,
//        "log" -> other,
//        "cpanel" -> hws,
//        "site" -> hws,
//        "smtp" -> el,
//        "card" -> other,
//        "crypt" -> c,
//        "db" -> ba,
//        "proxi" -> hws,
//        "mix install" -> mi,
//        "pack" -> exploits,
//        "passport" -> other,
//        "ddos" -> other,
//        "install" -> mi,
//        "domain" -> vh,
//        "acc" -> ba,
//        "login" -> ba,
//        "crack" -> other,
//        "project" -> other, 
//        "us install" -> mi,
//        "crypting service" -> c,
//        "buying install" -> mi,
//        "fr email" -> el,
//        "youtube account" -> ba,
//        "rootkit" -> exploits,
//        "email" -> el,
//        "hotmail account" -> el,
//        "cryptor" -> c,
//        "ddos bot" -> other,
//        "uk install" -> mi,
//        "de install" -> mi,
//        "traffic-install" -> mi)
    
  val productTypeMapping = new HashMap[String,(String,String)]() ++ Seq(
"-rsb- bot" -> (mi, s),
"0day-exploit" -> (m, p),
"1,000 account" -> (ba, p),
"10k install" -> (mi, s),
"200 bot" -> (mi, s),
"200 install" -> (mi, p),
"200-300 install" -> (mi, p),
"300 install" -> (mi, p),
"30k bot" -> (mi, s),
"360 account" -> (ha, p),
"500 install" -> (mi, p),
"75k email" -> (sp, p),
"<fud>" -> (c, p),
"abnormalstress" -> (st, s),
"access" -> (h, s),
"addmefast account" -> (ba, p),
"addmefast bot" -> (sp, p),
"admin" -> (hs, p),
"advertising service" -> (ss, s),
"adware-adbot" -> (m, p),
"adwords account" -> (ha, p),
"adworkmedia account" -> (ha, p),
"an account" -> (ha, p),
"android install" -> (mi, p),
"anti-doxing service" -> (b, s),
"aol account" -> (ba, p),
"aol email" -> (ba, p),
"api" -> (d, ""),
"applet" -> (d, ""),
"article" -> (b, p),
"ass-kissing service" -> (b, s),
"assignment service" -> (b, s),
"assignment" -> (b, ""),
"assistance service" -> (b, s),
"attack service" -> (h, s),
"attack" -> (h, ""),
"autorun.inf" -> (m, p),
"ayocrypt" -> (c, p),
"azure account" -> (ha, p),
"backconnect" -> (pr, s),
"backlink service" -> (ss, s),
"backlink" -> (ss, s),
"backlinks service" -> (ss, s),
"bank account" -> (ha, p),
"bank-account" -> (ha, p),
"base" -> (h, ""),
"battle.net account" -> (ha, p),
"battlenet account" -> (ha, p),
"best-boot" -> (st, s),
"betaboot" -> (st, s),
"bin-source" -> (d, ""),
"bind" -> (m, p),
"binder/crypter/pack" -> (m, p),
"binding service" -> (m, s),
"bombing service" -> (ss, s),
"boost" -> (vgs, s),
"boosting service" -> (vgs, s),
"boosting/leveling service" -> (vgs, s),
"boot" -> (st, s),
"booter account" -> (ha, p),
"booting service" -> (st, s),
"botmail" -> (sp, p),
"botnet" -> (m, p),
"botnet/rat/epk" -> (m, p),
"bots/slav" -> (m, ""),
"botshop install" -> (mi, p),
"botshop" -> (mi, s),
"botting service" -> (h, s),
"bruteforc" -> (m, p),
"bruteforce" -> (h, s),
"bruterforc" -> (m, ""),
"building service" -> (vgs, s),
"bulk email" -> (ss, s),
"bulk" -> (ss, ""),
"buy bot" -> (sp, p),
"buy install" -> (mi, p),
"buying bot" -> (mi, s),
"bypass" -> (m, ""),
"bypassing email" -> (ss, s),
"c" -> (d, ""),
"c#" -> (d, ""),
"c&c" -> (m, ""),
"c++" -> (d, s),
"canada bot" -> (mi, s),
"canada-uk" -> (mi, s),
"card" -> (h, p),
"cheat" -> (vg, ""),
"chilean install" -> (mi, s),
"chillstress" -> (st, s),
"chl install" -> (mi, s),
"cl bot" -> (mi, s),
"clans account" -> (ha, p),
"clans bot" -> (pr, ""),
"clash account" -> (ha, p),
"clash" -> (vg, ""),
"class" -> (b, ""),
"classes service" -> (b, s),
"coaching service" -> (b, s),
"coaching/boosting service" -> (vgs, s),
"coc account" -> (ha, p),
"cod" -> (vg, ""),
"code bot" -> (d, p),
"code" -> (d, s),
"code/program" -> (d, s),
"coder" -> (d, s),
"coding service" -> (s, ""),
"coding/hacking/anyth" -> (h, s),
"coding/math/homework service" -> (b, s),
"commenting bot" -> (sp, p),
"complexstresser.net" -> (st, s),
"cpanel" -> (hs, p),
"cpanels account" -> (ha, p),
"cpanl" -> (hs, p),
"crack account" -> (ha, p),
"crack" -> (h, s),
"cracked account" -> (ha, p),
"craigslist account" -> (ba, p),
"creation/programm" -> (d, s),
"crpyt" -> (c, ""),
"crypt service" -> (cs, s),
"crypt" -> (c, p),
"crypter service" -> (cs, s),
"crypter" -> (c, p),
"crypter-crypt service" -> (cs, s),
"crypticaccount" -> (cs, s),
"crypting service" -> (cs, s),
"cryptor" -> (c, p),
"cryptor-pack" -> (c, p),
"cryptservice" -> (cs, s),
"crystalstress" -> (st, s),
"cs-go account" -> (ha, p),
"csgo account" -> (ha, p),
"csgo/css/l4d2" -> (vg, ""),
"cubeworld account" -> (ha, p),
"customer service" -> (b, s),
"d0x service" -> (h, s),
"darkbooter account" -> (ha, p),
"darkcomet" -> (m, ""),
"databas" -> (h, p),
"database" -> (h, p),
"database-mysql" -> (h, p),
"db account" -> (ha, p),
"db" -> (h, p),
"ddos bot" -> (m, p),
"ddos service" -> (st, s),
"ddos" -> (st, s),
"ddosing service" -> (st, s),
"de install" -> (mi, s),
"deathbycaptcha account" -> (ha, p),
"design service" -> (b, s),
"design" -> (b, s),
"designing service" -> (b, s),
"dev" -> (d, s),
"develop" -> (d, s),
"developement service" -> (b, s),
"developer account" -> (a, p),
"developing bot" -> (m, s),
"development service" -> (b, s),
"dislike/flag bot" -> (sp, p),
"dll" -> (d, ""),
"dogeboot" -> (st, s),
"dogestress" -> (st, s),
"domain" -> (ho, s),
"domaintools.com account" -> (ha, p),
"download service" -> (h, s),
"downloader" -> (m, p),
"dox service" -> (h, s),
"dox" -> (h, s),
"doxing service" -> (h, s),
"drop" -> (mi, s),
"dropping service" -> (h, s),
"dstat service" -> (st, s),
"dstat" -> (st, s),
"dump" -> (h, p),
"e-whore service" -> (b, s),
"ebay.de account" -> (ba, p),
"editing service" -> (b, s),
"edu email" -> (ha, p),
"edu.eg email" -> (ha, p),
"eloboost service" -> (vgs, s),
"eloboost" -> (vgs, s),
"email account" -> (ba, p),
"email service" -> (ss, s),
"email" -> (sp, p),
"emails-hashes-salt" -> (ha, p),
"encrypt" -> (c, p),
"encryption" -> (c, p),
"erastress" -> (st, s),
"es install" -> (mi, s),
"escrow service" -> (b, s),
"essay service" -> (b, s),
"essay" -> (b, s),
"exacttarget.com account" -> (ha, p),
"exp service" -> (vgs, s),
"expliot" -> (m, ""),
"exploit" -> (m, p),
"exploiter/boot" -> (m, ""),
"extremestress" -> (st, s),
"facebook account" -> (ba, p),
"farming bot" -> (pr, ""),
"fastflux service" -> (h, s),
"fb account" -> (ba, p),
"flood service" -> (st, s),
"flood" -> (st, s),
"flux bot" -> (m, p),
"flux" -> (m, p),
"follow" -> (ss, s),
"follower bot" -> (sp, p),
"formgrabb" -> (m, p),
"fr bot" -> (mi, s),
"france bot" -> (mi, s),
"french service" -> (b, s),
"fresh email" -> (ba, p),
"fresh install" -> (mi, s),
"ftp account" -> (ha, p),
"ftpstres" -> (st, s),
"fud service" -> (cs, s),
"fud" -> (c, p),
"fud-crypt" -> (c, p),
"fudding service" -> (cs, s),
"gam" -> (vg, ""),
"game" -> (vg, ""),
"gamebattles account" -> (ha, p),
"gamertag" -> (vg, ""),
"gameshare" -> (vg, ""),
"gaming account" -> (ha, p),
"gb account" -> (ha, p),
"gbot" -> (m, p),
"gfx" -> (b, ""),
"gmail account" -> (ba, p),
"gmail service" -> (h, s),
"go account" -> (ha, p),
"godaddy account" -> (ha, p),
"gold" -> (vg, p),
"gold/item" -> (vg, ""),
"google account" -> (ba, p),
"hack service" -> (h, s),
"hack" -> (h, s),
"hacking service" -> (h, s),
"hackz" -> (h, ""),
"hero" -> (vg, ""),
"high-traf" -> (t, ""),
"hijacking service" -> (h, s),
"hitleap account" -> (ba, p),
"homeowork service" -> (b, s),
"homework service" -> (b, s),
"homework" -> (b, s),
"homework/coursework service" -> (b, s),
"homework/projects/essay" -> (b, ""),
"host" -> (ho, s),
"hosting account" -> (ha, p),
"hosting service" -> (ho, s),
"hotmail account" -> (ba, p),
"hotmail" -> (ba, p),
"hotmail.com account" -> (ba, p),
"hotmail/live email" -> (ba, p),
"http bot" -> (m, p),
"http" -> (cs, s),
"https" -> (ha, p),
"iframe" -> (m, p),
"iframer bot" -> (m, p),
"inbox" -> (ss, s),
"infect service" -> (h, s),
"infecting service" -> (h, s),
"infections service" -> (h, s),
"inject" -> (m, p),
"injector" -> (m, p),
"insta" -> (mi, p),
"instagram account" -> (ba, p),
"instagram bot" -> (sp, p),
"instagram service" -> (ss, s),
"instahijack service" -> (h, s),
"install" -> (mi, s),
"installs-updat" -> (mi, p),
"installs/updates/load" -> (mi, s),
"instinctboot" -> (st, s),
"invite" -> (b, ""),
"ipstresser.com account" -> (ha, p),
"irc bot" -> (m, p),
"isteal" -> (m, p),
"italian bot" -> (mi, s),
"italy bot" -> (mi, s),
"itunes account" -> (a, p),
"jacking service" -> (h, s),
"jailbreaking service" -> (b, s),
"javascript" -> (d, ""),
"jrat install" -> (mi, p),
"jumpvpn" -> (pr, s),
"keylogg" -> (m, p),
"kik" -> (ba, p),
"kingstress" -> (st, s),
"kw install" -> (mi, s),
"laptop" -> (b, ""),
"latin-spanish install" -> (mi, s),
"league account" -> (ha, p),
"league" -> (vg, ""),
"legends account" -> (ha, p),
"legit account" -> (ha, p),
"lesson" -> (b, s),
"level account" -> (vg, ""),
"level" -> (vg, ""),
"leveling service" -> (vgs, s),
"levelling service" -> (vgs, s),
"like/comment/follow bot" -> (sp, p),
"limeflood" -> (m, ""),
"link" -> (ss, s),
"linux bot" -> (m, p),
"linuxbot" -> (m, p),
"list" -> (sp, p),
"live account" -> (ba, p),
"live email" -> (ba, p),
"load" -> (mi, s),
"log" -> (h, s),
"login" -> (ha, p),
"lol account" -> (ha, p),
"lol service" -> (vgs, ""),
"loleboost" -> (vg, ""),
"lunarbot" -> (m, ""),
"lvl service" -> (vgs, s),
"lvl" -> (vg, ""),
"mail account" -> (ha, p),
"mail" -> (ss, s),
"mailing service" -> (ss, s),
"mailinglist" -> (sp, p),
"maill" -> (sp, p),
"maillist" -> (sp, p),
"mailspam" -> (sp, p),
"malware" -> (m, p),
"mass email" -> (ss, s),
"mentoring service" -> (b, s),
"merchant account" -> (ha, p),
"messaging bot" -> (sp, p),
"miles-and-more account" -> (ha, p),
"million email" -> (sp, p),
"mincraft account" -> (ha, p),
"minecraft account" -> (ha, p),
"minecraft" -> (vg, s),
"minecraft/netflix account" -> (ha, p),
"mixed install" -> (mi, p),
"mlg account" -> (ha, p),
"mn0g0.cc account" -> (ha, p),
"mod service" -> (vgs, s),
"mod" -> (vg, ""),
"modd" -> (vg, s),
"modding service" -> (vgs, s),
"msdn account" -> (ha, p),
"msn account" -> (ba, p),
"mx install" -> (mi, s),
"my bot" -> (m, p),
"need bot" -> (m, p),
"netflix account" -> (ha, p),
"netflix" -> (ha, p),
"netflix/mc/spotify account" -> (ha, p),
"network" -> (ho, s),
"ngrbot" -> (m, p),
"non-generated account" -> (ha, p),
"nulledstress" -> (st, s),
"nz bot" -> (mi, s),
"ocr" -> (ss, s),
"ocr-acr" -> (sp, p),
"ocstress" -> (st, s),
"online bot" -> (m, p),
"optimalstress" -> (st, s),
"outlook email" -> (ba, p),
"outlook.com email" -> (ba, p),
"pack" -> (m, p),
"packer-cryptor" -> (c, p),
"panel account" -> (ha, p),
"panel" -> (hs, p),
"pass" -> (ha, p),
"pastebin bot" -> (sp, p),
"paypal account" -> (ba, p),
"paypal email" -> (ha, p),
"paypal" -> (ha, p),
"pbe account" -> (ha, p),
"pentesting service" -> (h, s),
"photoshop service" -> (b, s),
"php-mailer-smtp" -> (st, p),
"phpshell" -> (hs, p),
"playstation account" -> (ha, p),
"playstation" -> (vg, ""),
"pop3" -> (ss, s),
"posting service" -> (ss, s),
"pow" -> (vg, ""),
"power-stress" -> (st, s),
"powerlevel" -> (vg, s),
"powerleveling service" -> (vgs, s),
"powerleveling/gold service" -> (vgs, s),
"powerstress" -> (st, s),
"pp" -> (ha, p),
"ppi install" -> (mi, p),
"pr" -> (ss, s),
"primeboot" -> (st, s),
"primebooter account" -> (ha, p),
"product" -> (u, p),
"program" -> (d, s),
"programm" -> (d, s),
"programme" -> (d, s),
"programming service" -> (pr, s),
"project" -> (d, ""),
"proof" -> (ho, s),
"proof-reading service" -> (b, s),
"proofread" -> (b, s),
"proofreading service" -> (b, s),
"proxi" -> (pr, s),
"proxy install" -> (mi, s),
"proxy service" -> (pr, s),
"proxy" -> (pr, s),
"ps3 account" -> (ha, p),
"ps3 service" -> (vgs, s),
"ps3" -> (vg, ""),
"ps3/ps4/playstation account" -> (ha, p),
"ps4 account" -> (ha, p),
"ps4" -> (vg, ""),
"psn account" -> (ha, p),
"psn" -> (vg, ""),
"pw email" -> (ha, p),
"quality install" -> (mi, p),
"quest" -> (vg, ""),
"questing service" -> (vgs, s),
"r00t" -> (hs, p),
"rank" -> (vgs, s),
"ranking service" -> (vgs, s),
"rat service" -> (h, s),
"rat" -> (m, p),
"rat/logg" -> (m, p),
"ratting service" -> (h, s),
"razorcrypt" -> (c, ""),
"razorstress" -> (st, s),
"rdp account" -> (hs, p),
"rdp" -> (hs, p),
"rdps" -> (hs, p),
"recoveri" -> (h, ""),
"recovery service" -> (h, s),
"recovery" -> (h, s),
"reddit account" -> (ha, p),
"referrals/accounts/boost" -> (vg, s),
"registration service" -> (ss, s),
"removal service" -> (h, s),
"renting bot" -> (mi, s),
"reply bot" -> (sp, p),
"resolv" -> (st, s),
"rewards account" -> (ha, p),
"rgh/jtag install" -> (mi, p),
"rift bot" -> (sp, p),
"root" -> (hs, p),
"rootkit" -> (m, p),
"scan" -> (m, p),
"scann" -> (m, p),
"scrap" -> (ss, s),
"script" -> (d, ""),
"sdk" -> (d, ""),
"selling install" -> (mi, p),
"seo service" -> (ss, s),
"seo" -> (ss, s),
"server" -> (ho, s),
"setup service" -> (h, s),
"setup" -> (m, s),
"shell" -> (h, s),
"shells-cpanel" -> (hs, p),
"shells-roots-cpanels-whm-etc" -> (hs, p),
"shutdownstress" -> (st, s),
"sig" -> (b, ""),
"signatur" -> (b, ""),
"signature" -> (b, s),
"signing service" -> (ss, s),
"site" -> (d, ""),
"site" -> (hs, p),
"skin" -> (vgs, s),
"skype account" -> (ba, p),
"skype bot" -> (sp, p),
"smoke bot" -> (m, p),
"smtp" -> (ss, s),
"smtp-rdp" -> (hs, p),
"smtp/cpanel/webmail" -> (hs, p),
"snapchat" -> (ba, p),
"sock" -> (pr, s),
"socks4-5" -> (pr, s),
"socks5-proxi" -> (pr, s),
"some account" -> (ha, p),
"soundcloud bot" -> (sp, p),
"sourc" -> (d, ""),
"source" -> (d, p),
"sourcecode" -> (d, p),
"spam bot" -> (sp, p),
"spam service" -> (ss, s),
"spam" -> (ss, s),
"spambot" -> (sp, p),
"spammer bot" -> (sp, p),
"spamming bot" -> (sp, p),
"speaker-translator" -> (b, ""),
"spinning service" -> (ss, s),
"sploit" -> (m, p),
"spoof" -> (st, s),
"spotify account" -> (ba, p),
"spread service" -> (h, s),
"spread" -> (h, s),
"spreading service" -> (h, s),
"spreading/crypt" -> (cs, s),
"spy-eye" -> (m, p),
"stable bot" -> (mi, s),
"stacked account" -> (ba, p),
"starbucks account" -> (ha, p),
"starcraft" -> (vg, ""),
"starwoods account" -> (ha, p),
"steal" -> (h, s),
"stealing service" -> (h, s),
"steam account" -> (ha, p),
"steam" -> (ha, p),
"stres" -> (st, s),
"stress" -> (st, s),
"stressem-network" -> (st, s),
"stresser account" -> (ha, p),
"stresser.ru" -> (st, s),
"stresser/boot" -> (st, s),
"stressing.pw" -> (st, s),
"strike" -> (vg, ""),
"stub" -> (c, p),
"subscriber bot" -> (sp, p),
"survey" -> (b, ""),
"switzerland bot" -> (mi, s),
"t-shirt" -> (b, ""),
"tag" -> (vg, ""),
"tagged.me account" -> (ba, p),
"teamview" -> (m, p),
"testimonial/spokesperson service" -> (b, s),
"the account" -> (a, p),
"this account" -> (a, p),
"topdogtraffic" -> (t, s),
"track2 account" -> (ha, p),
"traf" -> (t, ""),
"traff" -> (t, ""),
"traff-sit" -> (t, ""),
"traffic bot" -> (m, p),
"traffic service" -> (t, s),
"traffic" -> (t, p),
"traffic-install" -> (mi, s),
"translating service" -> (b, s),
"translation service" -> (b, s),
"translation" -> (b, s),
"triggerbot" -> (vg, p),
"trojan bot" -> (m, p),
"trojan" -> (m, p),
"tumblr account" -> (ba, p),
"tumblr bot" -> (sp, p),
"tumblr" -> (ba, p),
"tutor" -> (b, s),
"tutor/homework service" -> (b, s),
"tutoring service" -> (b, s),
"twitch account" -> (ha, p),
"twitch bot" -> (sp, p),
"twitch" -> (vg, ""),
"twitch.tv account" -> (ha, p),
"twitch.tv bot" -> (sp, p),
"twitchtv/justintv bot" -> (sp, p),
"twitter account" -> (ba, p),
"twitter bot" -> (sp, p),
"twitter-fb account" -> (ba, p),
"uk bot" -> (mi, s),
"uk install" -> (mi, s),
"umg account" -> (ha, p),
"unchecked account" -> (ha, p),
"unlocking service" -> (s, ""),
"uplay account" -> (ha, p),
"upload" -> (mi, s),
"ups account" -> (ha, p),
"us bot" -> (mi, s),
"usa bot" -> (mi, s),
"vba" -> (d, ""),
"vcc service" -> (ba, p),
"vcc" -> (ba, p),
"verfied account" -> (ba, p),
"video" -> (vg, s),
"view bot" -> (sp, p),
"viewerbot" -> (sp, p),
"views account" -> (ba, p),
"views service" -> (ss, s),
"views/traffic" -> (ss, s),
"vine account" -> (ba, p),
"voice account" -> (ba, p),
"voiceover service" -> (b, s),
"voting bot" -> (sp, p),
"vouch" -> (b, ""),
"vpn account" -> (pr, s),
"vpn service" -> (pr, s),
"vpn" -> (pr, s),
"vps" -> (ho, s),
"vps" -> (pr, s),
"vulnerability service" -> (h, s),
"warcraft account" -> (ha, p),
"watson account" -> (ha, p),
"web-boot" -> (st, s),
"webdesign" -> (b, ""),
"webinject" -> (m, p),
"webmoney account" -> (ha, p),
"webshell" -> (hs, p),
"website" -> (d, ""),
"website/program" -> (pr, s),
"webstress" -> (st, s),
"westernunion.com account" -> (ha, p),
"winsocks.net account" -> (ha, p),
"wiredcrypt" -> (c, p),
"with account" -> (ha, p),
"world" -> (vg, ""),
"wow account" -> (ha, p),
"wow" -> (vg, ""),
"writing service" -> (b, s),
"xbl" -> (vg, ""),
"xbox account" -> (ha, p),
"xbox" -> (vg, ""),
"xtremestress" -> (st, s),
"yahoo email" -> (ba, p),
"youtube account" -> (ba, p),
"youtube bot" -> (m, p),
"youtube bot" -> (sp, p),
"zeu" -> (m, p))

  
  def canonicalize(fullProduct: String, semanticProduct: String, head: String): (String, String) = {
    val retrievedTypes = if (productTypeMapping.contains(semanticProduct)) {
      productTypeMapping(semanticProduct)
    } else if (productTypeMapping.contains(head)) {
      productTypeMapping(head)
    } else {
      (other, u)
    }
    (if (retrievedTypes._1 == "") other else retrievedTypes._1) -> (if (retrievedTypes._2 == "") u else retrievedTypes._2) 
  }
  
  def processAnnotatedFile(file: String) {
    val damonFileItr = IOUtils.lineIterator(IOUtils.openInHard(file))
    while (damonFileItr.hasNext) {
      val line = damonFileItr.next.trim
      if (line.contains(";")) {
        val word = line.substring(0, line.indexOf(":"))
        val firstSemi = line.indexOf(";")
        val lastSemi = line.lastIndexOf(";")
        val (fineCat, coarseCat) = if (firstSemi == lastSemi) {
          (line.substring(firstSemi + 1), "")
        } else {
          // Both exist
          (line.substring(firstSemi + 1, lastSemi), line.substring(lastSemi + 1))
        }
        Logger.logss("\"" + word + "\" -> (" + fineCat + ", " + (if (coarseCat.isEmpty) "\"\"" else coarseCat) + "),")
      }
    }
  }
  
  def main(args: Array[String]) {
    processAnnotatedFile("data/hackforums-keywords-damon.txt")
    processAnnotatedFile("data/darkode-keywords-damon.txt")
  }
}
